/* Generated by experiment/crypto-pipeline/generate.mjs. DO NOT EDIT BY HAND.
 * Bundle ID: e4408d902149
 * Algorithm: sbox-cbc-inverse (response decrypt), 3 rounds.
 * Round: out[i] = invSbox[in[i]] ^ in[i-1] ^ key[i % key.length]   (in[-1] = iv)
 * Applied for stages 1..N. Verified byte-exact against the live bundle.
 */

const B64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

function b64Decode(s: string): number[] {
    const lookup: number[] = new Array(128).fill(-1);
    for (let i = 0; i < 64; i++) lookup[B64_CHARS.charCodeAt(i)] = i;
    const normalized = s.replace(/-/g, "+").replace(/_/g, "/");
    const out: number[] = [];
    let buf = 0, bits = 0;
    for (let i = 0; i < normalized.length; i++) {
        const c = normalized.charCodeAt(i);
        if (c === 61) break; // '='
        const v = lookup[c] ?? -1;
        if (v < 0) continue;
        buf = (buf << 6) | v;
        bits += 6;
        if (bits >= 8) { bits -= 8; out.push((buf >> bits) & 0xff); }
    }
    return out;
}

// Inverse-permutation cache, keyed by the stage's forward S-box base64.
const INV_CACHE: Record<string, number[]> = {};
function inverseSbox(tableB64: string): number[] {
    const cached = INV_CACHE[tableB64];
    if (cached) return cached;
    const table = b64Decode(tableB64);
    const inv: number[] = new Array(256).fill(0);
    for (let i = 0; i < 256; i++) inv[table[i]!] = i;
    INV_CACHE[tableB64] = inv;
    return inv;
}
const KEY_CACHE: Record<string, number[]> = {};
function keyBytes(keyB64: string): number[] {
    const cached = KEY_CACHE[keyB64];
    if (cached) return cached;
    const k = b64Decode(keyB64);
    KEY_CACHE[keyB64] = k;
    return k;
}

const DECRYPT_STAGES: { sboxB64: string; keyB64: string; iv: number }[] = [
    {
        "sboxB64": "hhNit22WWR9Nu5X7+UnED8bRkN15Akxr6qbiahmrx6eKUI1AlHRXBUf0YTApaf/XSE64vSK8NuTbU7qfpc4QyP7JKBQnrDfBDCRu2FxgiN6eaIkds8BbfSPW7zuYfv367cJwC8y+P7ld36PKgAOp4FXLCe6PokHmdrbsw82uSwFa1XH1rWwWByuHghoc4SHl8TqBZTx/hIva9jKh52MbhT1Pew1DGF9UqhXrk0rcRAh3ejWMIDMXtPec8rKdRenS/AAefLCZr3J1MSoGLyYEz7GgLTRvxfPQWPCal1JzOPibLA7UVuN4v+iDXlESOSVnCi612RFmZEZCqJGSPqSO0w==",
        "keyB64": "AoxInIinOt6G8seYoJix/iN/",
        "iv": 232
    },
    {
        "sboxB64": "8ID4yalwCgxqUunAT/owdkkERUJv/zi1678e2tMmqIhO1WGL7uYOV/RUrEZxFgEzWRM/NQVdlorG0i+ZWuGn/bvg2Y0nIery4w2J6CIdXCw6dWzkmPP1z7S+ehWdtv6DbV/YNIxHG8wkGpOiYEpu8bML+bID1t14j+32K9yGTGaww+xkdN7HB7H3lUMxlOIYI71yyhHEIHwq561rRKAJ25sGvOWahBc+SFEPW8L8f35oczdNU9EpoRSX+wimNoGQaS4cPZE7zYc8gp7Oqu/Qq99eEFW6hRmSd0F9pLnIOSiOrpy4e2dYAMGlYp9lo0ASt9QlUC0fY68yVgLF10vLeQ==",
        "keyB64": "3EZs0aj6HfXoPsLi8vJW1JqqxR6gywB4WfNwYg==",
        "iv": 89
    },
    {
        "sboxB64": "7Zz7Fb6E1Tts/kAtobexmz9jiHyWYM0rA7noGa/zeHrBFpVpDNPXVlXELPn9QeESDXa6i07lRV6jIOMBWRQIBySnN60zrAWMNYWgBBiDAvbDND3s0Vg+90M6R/Gl75gqmmR/Ntpzu45QrsjnTfwPd2ardHEv8ikctNyZ1miBJ7a/aiWKYUkTsiIApt0L+PCp5HuQOMAhncwdXQpKpFt9qjll9QZuRM4avVJU7sL6s48mdWIea8eRT0iiV7C8h8kxZ40fedjeI89tcDLSiUbGTC7UMFHmbxGUS5OoKMtTtQmX6lyeuFpfftCA6f/g9Ns82ZKfcheGDuKCG8rfQhDrxQ==",
        "keyB64": "lngA+TKmLX5HeI08Xvhin05wqg==",
        "iv": 38
    }
];

function decryptRound(data: number[], sboxB64: string, keyB64: string, iv: number): number[] {
    const inv = inverseSbox(sboxB64);
    const key = keyBytes(keyB64);
    const out: number[] = new Array(data.length);
    let prev = iv & 0xff;
    for (let i = 0; i < data.length; i++) {
        const c = data[i]! & 0xff;
        out[i] = (inv[c]! ^ prev ^ key[i % key.length]!) & 0xff;
        prev = c;
    }
    return out;
}

// Manual UTF-8 decode (JavaScriptCore-safe; no TextDecoder dependency).
function utf8Decode(bytes: number[]): string {
    let out = "";
    let i = 0;
    const n = bytes.length;
    while (i < n) {
        const b = bytes[i++]! & 0xff;
        if (b < 0x80) {
            out += String.fromCharCode(b);
        } else if (b < 0xe0) {
            out += String.fromCharCode(((b & 0x1f) << 6) | (bytes[i++]! & 0x3f));
        } else if (b < 0xf0) {
            const b1 = bytes[i++]! & 0x3f, b2 = bytes[i++]! & 0x3f;
            out += String.fromCharCode(((b & 0x0f) << 12) | (b1 << 6) | b2);
        } else {
            const b1 = bytes[i++]! & 0x3f, b2 = bytes[i++]! & 0x3f, b3 = bytes[i++]! & 0x3f;
            let cp = ((b & 0x07) << 18) | (b1 << 12) | (b2 << 6) | b3;
            cp -= 0x10000;
            out += String.fromCharCode(0xd800 + (cp >> 10), 0xdc00 + (cp & 0x3ff));
        }
    }
    return out;
}

function normalizeHeaders(headers: Record<string, string>): Record<string, string> {
    const out: Record<string, string> = {};
    for (const key of Object.keys(headers ?? {})) out[key.toLowerCase()] = String(headers[key]);
    return out;
}

/**
 * Decrypt a comix.to encrypted API envelope ({ e: "<base64>" }) to its parsed
 * result. Pass-through when the payload is not encrypted. Mirrors the bundle's
 * response interceptor, including the { status: "ok", result } unwrap.
 */
export function fastDecryptComixPayload(rawPath: string, payload: any, headers: Record<string, string> = {}): any {
    void rawPath;
    if (!(payload && typeof payload === "object" && typeof payload.e === "string")) return payload;
    const h = normalizeHeaders(headers);
    if (h["x-enc"] && h["x-enc"] !== "1") return payload;

    let data = b64Decode(payload.e);
    for (const stage of DECRYPT_STAGES) data = decryptRound(data, stage.sboxB64, stage.keyB64, stage.iv);

    const parsed = JSON.parse(utf8Decode(data));
    return parsed && typeof parsed === "object" && parsed.status === "ok" && "result" in parsed ? parsed.result : parsed;
}
