/* Generated by experiment/crypto-pipeline/generate.mjs. DO NOT EDIT BY HAND.
 * Bundle ID: 6ffb1349405a
 * Algorithm: sbox-cbc (request signer), 3 rounds.
 * Round: out[i] = sbox[in[i] ^ out[i-1] ^ key[i % key.length]]   (out[-1] = iv)
 * Applied for stages N..1 (reverse of decrypt). Verified against the live token.
 */

const B64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

function b64Decode(s: string): number[] {
    const lookup: number[] = new Array(128).fill(-1);
    for (let i = 0; i < 64; i++) lookup[B64_CHARS.charCodeAt(i)] = i;
    const normalized = s.replace(/-/g, "+").replace(/_/g, "/");
    const out: number[] = [];
    let buf = 0, bits = 0;
    for (let i = 0; i < normalized.length; i++) {
        const c = normalized.charCodeAt(i);
        if (c === 61) break; // '='
        const v = lookup[c] ?? -1;
        if (v < 0) continue;
        buf = (buf << 6) | v;
        bits += 6;
        if (bits >= 8) { bits -= 8; out.push((buf >> bits) & 0xff); }
    }
    return out;
}

// Inverse-permutation cache, keyed by the stage's forward S-box base64.
const INV_CACHE: Record<string, number[]> = {};
function inverseSbox(tableB64: string): number[] {
    const cached = INV_CACHE[tableB64];
    if (cached) return cached;
    const table = b64Decode(tableB64);
    const inv: number[] = new Array(256).fill(0);
    for (let i = 0; i < 256; i++) inv[table[i]!] = i;
    INV_CACHE[tableB64] = inv;
    return inv;
}
const KEY_CACHE: Record<string, number[]> = {};
function keyBytes(keyB64: string): number[] {
    const cached = KEY_CACHE[keyB64];
    if (cached) return cached;
    const k = b64Decode(keyB64);
    KEY_CACHE[keyB64] = k;
    return k;
}

const SIGN_STAGES: { sboxB64: string; keyB64: string; iv: number }[] = [
    {
        "sboxB64": "9B40/GuUkfsnsl9KYcKsFQZuAAMq+kyIKyaFlexTNwo2GZtvF2BEMzmnhhJB61fJk/50cyNQzLvULPCrYxjqmnxCsE4aYjhb6bp6T/Fnlx97GxGtoln/xSLO4uMEXaPXFEmKyAGEWkNoDUe4cam1E9F48p3bFn7dpVGoZcH4PTHSVefkRVTGCy71kkjz1XZNCeg8LflsaXVm9h2eJOAvzzvmBdOuMonEKZ95ze6/P1IovhAC2bSZudChx1zfs0ZWfweH2MqAwCGPDzo1gbZq4Q6kbQggcqravZhejPdAt40+HJDvsXevMEuLDMOCpmSc/ZbLg1gl7eXW3qBwvNyOfQ==",
        "keyB64": "fVmQlqjCTcUKxUv07hMRWu3nANZQ3A==",
        "iv": 253
    },
    {
        "sboxB64": "deT9YwpC6OHybKgqjpSXioNTFq1gguXPZQzHuw909Vpk1EbsLOC8xe7IkUQYK16e/PGEW1RiE1BoMHmqvwc9mvlZS1Vfc9qNwY8yzlZrktGbTbBvvQirMzyfMdx6gAQ6pK9RJvQR+ABDnHanL/coHSAFI21xUqAbBrSumClwJx/AxAmjTPuxzE/WC+sXd7c1EN6yoYnLP9+MFAKLah7nQRWpToG5h/q2DdmViDkO052F8CUBLkB+7SRmSRw05tA74u//0me4bqLXtS0ZRd18R5a+WNhhpckae82shgNcaco4mRJ480qQISLbNle6wrOTfelIN8P21aZd/nLGPuN/6g==",
        "keyB64": "hgEbN+jfedgmU34ZYtl607eO7o7l",
        "iv": 176
    },
    {
        "sboxB64": "C6w2gNnL9/1PqjMKxUGUbg+Jd/Hl42vUNGc5Exld71n4OtgpHlHae1BA4UOmFNCbK56dshBz0f9OnMiWaAN8ZkR2Bkm4MVNiTBqrmgEmmaJF9bOCxDXdAsqEfdcngZBjwh2nR2AOQtVwKA15jnVtXOn7YewWIAURUniuaUhGTZ8ySrt0hgn6kyLBtvKDV37wEnowxt6v4H/nl6g8JNzOvXLHKubP/iNbjd8fcTe3WqWKkhuwPy1Y7lRLaiEX6pGImIug08llLsA9PvnoBL7DtQiF8wwsjDsHJaOhtMzSHNbiqZVfrYe6Vblsb/yP2/brOPQv5LFeZM0AFRjtVr+kvA==",
        "keyB64": "a8Ch/pkYkJY0IMDnhyeFLa8=",
        "iv": 51
    }
];

function signRound(data: number[], sboxB64: string, keyB64: string, iv: number): number[] {
    const table = b64Decode(sboxB64);
    const key = keyBytes(keyB64);
    const out: number[] = new Array(data.length);
    let prev = iv & 0xff;
    for (let i = 0; i < data.length; i++) {
        const idx = ((data[i]! & 0xff) ^ prev ^ key[i % key.length]!) & 0xff;
        const next = table[idx]! & 0xff;
        out[i] = next;
        prev = next;
    }
    return out;
}

function b64UrlEncode(bytes: number[]): string {
    let out = "", i = 0;
    for (; i + 2 < bytes.length; i += 3) {
        const n = (bytes[i]! << 16) | (bytes[i + 1]! << 8) | bytes[i + 2]!;
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]! + B64_CHARS[(n >> 6) & 63]! + B64_CHARS[n & 63]!;
    }
    if (i + 1 === bytes.length) {
        const n = bytes[i]! << 16;
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]!;
    } else if (i + 2 === bytes.length) {
        const n = (bytes[i]! << 16) | (bytes[i + 1]! << 8);
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]! + B64_CHARS[(n >> 6) & 63]!;
    }
    return out.replace(/\+/g, "-").replace(/\//g, "_");
}

function normalizeSignPath(rawPath: string): string {
    return rawPath
        .replace(/^https?:\/\/[^/]+/, "")
        .replace(/^\/api\/v1/, "")
        .split("?")[0]!;
}

function bytesFromString(s: string): number[] {
    const out: number[] = new Array(s.length);
    for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i) & 0xff;
    return out;
}

/** Produce the comix.to `_` signing token for an API path. */
export function fastGenerateHash(rawPath: string): string {
    const path = normalizeSignPath(rawPath);
    let data = bytesFromString(path);
    for (let r = SIGN_STAGES.length - 1; r >= 0; r--) {
        const s = SIGN_STAGES[r]!;
        data = signRound(data, s.sboxB64, s.keyB64, s.iv);
    }
    return b64UrlEncode(data);
}
