/* Generated by experiment/crypto-pipeline/generate.mjs. DO NOT EDIT BY HAND.
 * Bundle ID: 4cb7eca97842
 * Algorithm: sbox-cbc (request signer), 5 rounds.
 * Round: out[i] = sbox[in[i] ^ out[i-1] ^ key[i % key.length]]   (out[-1] = iv)
 * Applied for stages N..1 (reverse of decrypt). Verified against the live token.
 */

const B64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

function b64Decode(s: string): number[] {
    const lookup: number[] = new Array(128).fill(-1);
    for (let i = 0; i < 64; i++) lookup[B64_CHARS.charCodeAt(i)] = i;
    const normalized = s.replace(/-/g, "+").replace(/_/g, "/");
    const out: number[] = [];
    let buf = 0, bits = 0;
    for (let i = 0; i < normalized.length; i++) {
        const c = normalized.charCodeAt(i);
        if (c === 61) break; // '='
        const v = lookup[c] ?? -1;
        if (v < 0) continue;
        buf = (buf << 6) | v;
        bits += 6;
        if (bits >= 8) { bits -= 8; out.push((buf >> bits) & 0xff); }
    }
    return out;
}

// Inverse-permutation cache, keyed by the stage's forward S-box base64.
const INV_CACHE: Record<string, number[]> = {};
function inverseSbox(tableB64: string): number[] {
    const cached = INV_CACHE[tableB64];
    if (cached) return cached;
    const table = b64Decode(tableB64);
    const inv: number[] = new Array(256).fill(0);
    for (let i = 0; i < 256; i++) inv[table[i]!] = i;
    INV_CACHE[tableB64] = inv;
    return inv;
}
const KEY_CACHE: Record<string, number[]> = {};
function keyBytes(keyB64: string): number[] {
    const cached = KEY_CACHE[keyB64];
    if (cached) return cached;
    const k = b64Decode(keyB64);
    KEY_CACHE[keyB64] = k;
    return k;
}

const SIGN_STAGES: { sboxB64: string; keyB64: string; iv: number }[] = [
    {
        "sboxB64": "en1TCoWqrAS05JxxPwh7o1zDuwXX+TQnRSjp8SHnK9xDl2XwMRWGuX+CzK9pAeUisJJk6kAq2Y6+N/6UoIMMS5qhTCkuGsVfSAu9ymJyJgmyxDiK3YmndJGlY8tg/9NC8yP2d/L7VHZNTtvB9NSxgHkZZ8gA+htznRSt0nAsXZV8/eM9vxDYqxOfYS0fGC/HixbPWJYPM0a6IAbvb5AdjSVZVZ7fayTWh/VuOU86UUo+6Bd1B1IDfklWhFe1aKSB5tp4m1oOZqj8xo+TQTyZwKa4jLYeqbdqmFBER9XubM68iN4yEuJbAg0R7LPC4BzJruHr9+1eOzDR+DZtzTXQog==",
        "keyB64": "R5KlWHZ69mr3SVxA+CAcXJFZYMdBMg==",
        "iv": 107
    },
    {
        "sboxB64": "8mVU5Parlr5mP2TC4YH/VWtsM3t97AlvfN6eo6mc5nfcxm716ku6cvxXDCxw5zT+MV223XqLLXj5XxXuldA1wU/Xk1K52dWHEiNtRBsrAqLfyM8yfh3rsLStNohKQ9RYJZlirIPzBE47vTjbhb8khhaCzISdkTcnItJoF+P6UANpHGcvByamGExBjQUZSCpqWuApIJfARc46+yifFLVCDgaYQNbKLsevpNpWXvhZ8T7JC1Gbc6gKqmAI5RF5xNjwTVMAcSF26BqzMKAfDdPNHpJh9MOUj0a7ssXiyz1HgKGnmluuf++MjtGx9xO8kEl07emluIkP/QG3OWNcihA8dQ==",
        "keyB64": "3jdTR5uwo09IjYYgTRll6ObM8BY=",
        "iv": 63
    },
    {
        "sboxB64": "y589erZ1BW86YLwuwCSbKfQ/gdNfc4BdszQAnP1CumZUB78NzWS1TDtollEmyWmIY0XqsNsU7ozWK8T2vbmNRI7Pd9WRH38P49gGGxinhqWygtdBAixYatTwUv/OWpkWYSAt6Z3mQPmLo3yvTpIxGrjD2d1wMlnR98jHVedblHi3gwoJHqzxwtCQS7Ed2vgXqzne9VxDKgEE3Efh87utDl7K6+08jwOiNzAl6As4xaiF+u++bWKEJ+VKfpNTnpqmxnt9IUmuRqD73yjibqR0MzUZDPxWUD7S5GyXHOAISPLMwXH+ZU2hIpWqEhBP7GuHNhV5dhFyqZgvI2eJtIpXEw==",
        "keyB64": "yzrD7PH5EnPv7/4FwVUcxy0h0wGLKA==",
        "iv": 187
    },
    {
        "sboxB64": "wTbQDcBTIwSbDyx0OyZbJ2HmJK9jTgwK6pfjnMaHyUjrbX6uMzlScAjgNcQdCUlzK6GSFSi5/xhqH9ykXRMl7jAhMrWWsLt1oEEZvFTfqhrUpmIpHlyMSk3a9ISlQPdQaMcU8ksS2TQGfLjszAciyta06FXhHJ9Ht4aV5ayOaQtk+umJeZF/2/vxbPC/moggWD26/j86yIB6w88CG55yN/arZ/XecV5We4WzmY1MeE+iQ83Vdm9RF3ey/G624l9go2uBWgVC5xaTlC0vneRF/Th9887XggGpPpCK0g7LqPg8RtjR3Ysuve9Zg5ixMY+tACoQEWbtp9MDV8K++WVExQ==",
        "keyB64": "AAmYyeZ+gUTrGFiHFWHrjVtbLEQ=",
        "iv": 216
    },
    {
        "sboxB64": "hU5wL6NIbXHwE8OVPzcc/AdEl83KCWp6dBWJUpRipAGESeueyMtjXHWoDRj/iwhMDC2/r5wijOauxrF/1Mk54LMgOOmnNVMq15Db7lqG7PK0AyEfbrkaYHZlrJriaLxz58DB5NGdn/2SQ/hR1TMPETLFBsyw5UfqwhZPBGkxu9Orzvpyiu8AbOEZd7c6WY+y0pObSm/+F4CNHaLE9Kk2NPkCuqUoXimIh9j1Ennz8V3dgWQbJE1XoLV+gyw8uGswezuYJtBUoWEeW6qZ2WYuC8cQttaRpkZFfNq+S/crQhQKXw6W41hn++2t3t9QPUBBfc8j9ugljlYFeD7cglW9Jw==",
        "keyB64": "KEq55J8TutS4Bb1wAWd9hVtZPsvBhNVPItmLBQ==",
        "iv": 184
    }
];

function signRound(data: number[], sboxB64: string, keyB64: string, iv: number): number[] {
    const table = b64Decode(sboxB64);
    const key = keyBytes(keyB64);
    const out: number[] = new Array(data.length);
    let prev = iv & 0xff;
    for (let i = 0; i < data.length; i++) {
        const idx = ((data[i]! & 0xff) ^ prev ^ key[i % key.length]!) & 0xff;
        const next = table[idx]! & 0xff;
        out[i] = next;
        prev = next;
    }
    return out;
}

function b64UrlEncode(bytes: number[]): string {
    let out = "", i = 0;
    for (; i + 2 < bytes.length; i += 3) {
        const n = (bytes[i]! << 16) | (bytes[i + 1]! << 8) | bytes[i + 2]!;
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]! + B64_CHARS[(n >> 6) & 63]! + B64_CHARS[n & 63]!;
    }
    if (i + 1 === bytes.length) {
        const n = bytes[i]! << 16;
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]!;
    } else if (i + 2 === bytes.length) {
        const n = (bytes[i]! << 16) | (bytes[i + 1]! << 8);
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]! + B64_CHARS[(n >> 6) & 63]!;
    }
    return out.replace(/\+/g, "-").replace(/\//g, "_");
}

// Manual UTF-8 encode (JavaScriptCore-safe; the bundle signs UTF-8 bytes, so
// non-ASCII query values — e.g. a unicode search keyword — must be encoded as
// UTF-8, not truncated per UTF-16 code unit).
function utf8Encode(s: string): number[] {
    const out: number[] = [];
    for (let i = 0; i < s.length; i++) {
        let cp = s.charCodeAt(i);
        if (cp >= 0xd800 && cp <= 0xdbff && i + 1 < s.length) {
            const lo = s.charCodeAt(i + 1);
            if (lo >= 0xdc00 && lo <= 0xdfff) { cp = 0x10000 + ((cp - 0xd800) << 10) + (lo - 0xdc00); i++; }
        }
        if (cp < 0x80) { out.push(cp); }
        else if (cp < 0x800) { out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f)); }
        else if (cp < 0x10000) { out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f)); }
        else { out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f)); }
    }
    return out;
}

function decodeComponent(s: string): string {
    try { return decodeURIComponent(s.replace(/\+/g, " ")); } catch (e) { void e; return s; }
}

// Reproduce the canonical query string the comix bundle signs (= what the server
// re-derives from the incoming request): qs.stringify with encode:false,
// arrayFormat:"indices", skipNulls:true, keys sorted by raw code unit. Reverse-
// engineered by decrypting live tokens (bundle 625d…) and fuzz-verified byte-exact
// vs the bundle across 3000 randomized param objects. Keys sort by base name (the
// part before the first "["), so a key and its array/nested children stay together;
// "name[]" arrays become "name[0]=…&name[1]=…" in document order; nested keys
// ("order[number]") are kept verbatim; values are RAW (URL-decoded), never re-encoded.
function canonicalizeQuery(rawQuery: string): string {
    if (!rawQuery) { return ""; }
    const groups: Record<string, string[]> = {};
    const arrayCounts: Record<string, number> = {};
    const parts = rawQuery.split("&");
    for (let p = 0; p < parts.length; p++) {
        const part = parts[p]!;
        if (!part) { continue; }
        const eq = part.indexOf("=");
        const key = decodeComponent(eq >= 0 ? part.slice(0, eq) : part);
        const value = decodeComponent(eq >= 0 ? part.slice(eq + 1) : "");
        let base: string;
        let rendered: string;
        if (key.slice(-2) === "[]") {
            base = key.slice(0, -2);
            const i = arrayCounts[base] ?? 0;
            arrayCounts[base] = i + 1;
            rendered = base + "[" + i + "]=" + value;
        } else {
            const bracket = key.indexOf("[");
            base = bracket >= 0 ? key.slice(0, bracket) : key;
            rendered = key + "=" + value;
        }
        if (groups[base]) { groups[base]!.push(rendered); }
        else { groups[base] = [rendered]; }
    }
    return Object.keys(groups).sort().map((b) => groups[b]!.join("&")).join("&");
}

function signString(s: string): string {
    let data = utf8Encode(s);
    for (let r = SIGN_STAGES.length - 1; r >= 0; r--) {
        const st = SIGN_STAGES[r]!;
        data = signRound(data, st.sboxB64, st.keyB64, st.iv);
    }
    return b64UrlEncode(data);
}

/**
 * Produce the comix.to `_` signing token for an API request. Since bundle
 * 625d… the signature covers the path AND the canonicalized query params —
 * pathname-only tokens now get 403 "Invalid token.". Accepts a full URL or a
 * bare path, with or without a query string.
 */
export function fastGenerateHash(rawPath: string): string {
    const stripped = rawPath.replace(/^https?:\/\/[^/]+/, "").replace(/^\/api\/v1/, "");
    const qIdx = stripped.indexOf("?");
    if (qIdx < 0) { return signString(stripped); }
    const path = stripped.slice(0, qIdx);
    const canonical = canonicalizeQuery(stripped.slice(qIdx + 1));
    return signString(canonical ? path + "?" + canonical : path);
}
