/* Generated by experiment/crypto-pipeline/generate.mjs. DO NOT EDIT BY HAND.
 * Bundle ID: 7f5eff7ebada
 * Algorithm: xor-offset (response decrypt, x-enc 2), 1024-byte table.
 *   ct = [h0, h1, body...]; off = ((h0 << 8) | h1) % K.length
 *   pt[i] = body[i] ^ K[(off + i) % K.length]
 * Verified byte-exact against the live bundle.
 */

const B64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

function b64Decode(s: string): number[] {
    const lookup: number[] = new Array(128).fill(-1);
    for (let i = 0; i < 64; i++) lookup[B64_CHARS.charCodeAt(i)] = i;
    const normalized = s.replace(/-/g, "+").replace(/_/g, "/");
    const out: number[] = [];
    let buf = 0, bits = 0;
    for (let i = 0; i < normalized.length; i++) {
        const c = normalized.charCodeAt(i);
        if (c === 61) break; // '='
        const v = lookup[c] ?? -1;
        if (v < 0) continue;
        buf = (buf << 6) | v;
        bits += 6;
        if (bits >= 8) { bits -= 8; out.push((buf >> bits) & 0xff); }
    }
    return out;
}

const X_ENC = "2";
const KEY_B64 = "cDNQYcFzO3AR9vKV8et8JNkOebp8PP11TcGlxXsoeMt1BFuv2iwnlwu7Jg+s8cuU8H5d9ONVhH4LJuUBaz9QvL06pn+Bf8YduuVx8Q1wkjo8/icdNOY40JZZeAE+dBDqJovgTiB+6r+aBaiX4RbywUzm8IiXZNrBcGjJDWK40wzHhLovM6viKdrA5B0D2OXOQMKZCpB84+VxmZN52SSBnzwA3a0XbSBko1Wh+y2x0WxdcsfhvGvW1rg5R787wZvW5hrCLd1sJn6yKQroj4xcwNcydlsyg1u63kUrEMwXXJhDjvh7RqqkAj8uowWUkx011H01RKy9TRws/zwuQam7ssq2G5hGRyGPYlUJLnEDM6pi47/wfNMO8i8HT/cL8FKDKRACWi1jdIKq1ehCGFvcWF/LCqeF2CO8XQbeM4l4hHhCnq0zundhWWp7YQpwEhIYzsp6u94insLyAWV8QoMG+2eiC0VimTnzCPTvb6HN/OOomkSblhSDYGxTWNQeLJ7FCTjK73Y+/QcQDIybmKC6NpUjmz5C893YqJXTsh7qdIRBj9vaXWuPM9XtY6U9Pf3esTuzLsAsitSeM4Zl2Fh7knia6GMnh8x5wtWSbBb0ukv1tlHyY5sD3YAkhHEEwpl7s/OEjGSVHLjTjSBbYI1jTZkkyoYiJNMwfrcd14qy6INwn4GSV9o/AY2TPTidwra5qLK05C6HWmZwn/vq5blJY8nGbHuEBuGowark4ooLM1h9bRMzCbBHMDenfc1xaH6rGI/ekdl+b8FrTs6gVFcnMW7t2xinoPCzOPGwhJ1Qh4jIPj4YajLhEsqZMa2tqhwtDXRCPKM8kea1vhdW07YezrvB7AWTwAjrvonyqIvka3sGSicUwgPFZPIqkniJMvvk2A7lQ5cELLb1wvryYlSAiBE2+gBnvnqj9hsnNPaDH92xL1/JHLJmwp6692OpqUf9s2KaqW90wqyaBlH8t0bYXFqCTdLcGM+mS1Bq+6NhBkXqfJ2odCItIF59NYoq5Ai19P1CS13YrZ5ixQH6fGFf1dNQrgIejZQztsMXKLMwwz4zqGLrdnQ7CleQwpEGB/2iOZFXyTizuGe2gTBJnYKhDdQqIRLh1nQun8jtX2wfQU+n51aWitPrSUQVEe6+SElJSnvU1hVSvtzeUmS0XXGeXtMUOQzVdSKjZ91dvYWjPsdL8DnsMSQyGV8HG5pXhzsWjFiTBVh9u5wULn537Xw1OMCbSlBj167XUmDF5LjzBb7vhOsTr9Ckr5oEbQxXA4FOQO0+epxlmTBieNwr3A/PzrLw3T2fjw4eQtT/373ZIg0P/7txtjsl4vh5U6hOF8Y5X6gPF75X/ScnCeBbwtBLeg==";
let KEY: number[] | null = null;

// Manual UTF-8 decode (JavaScriptCore-safe; no TextDecoder dependency).
function utf8Decode(bytes: number[]): string {
    let out = "";
    let i = 0;
    const n = bytes.length;
    while (i < n) {
        const b = bytes[i++]! & 0xff;
        if (b < 0x80) {
            out += String.fromCharCode(b);
        } else if (b < 0xe0) {
            out += String.fromCharCode(((b & 0x1f) << 6) | (bytes[i++]! & 0x3f));
        } else if (b < 0xf0) {
            const b1 = bytes[i++]! & 0x3f, b2 = bytes[i++]! & 0x3f;
            out += String.fromCharCode(((b & 0x0f) << 12) | (b1 << 6) | b2);
        } else {
            const b1 = bytes[i++]! & 0x3f, b2 = bytes[i++]! & 0x3f, b3 = bytes[i++]! & 0x3f;
            let cp = ((b & 0x07) << 18) | (b1 << 12) | (b2 << 6) | b3;
            cp -= 0x10000;
            out += String.fromCharCode(0xd800 + (cp >> 10), 0xdc00 + (cp & 0x3ff));
        }
    }
    return out;
}

function normalizeHeaders(headers: Record<string, string>): Record<string, string> {
    const out: Record<string, string> = {};
    for (const key of Object.keys(headers ?? {})) out[key.toLowerCase()] = String(headers[key]);
    return out;
}

/**
 * Decrypt a comix.to encrypted API envelope ({ e: "<base64>" }) to its parsed
 * result. Pass-through when the payload is not encrypted. Mirrors the bundle's
 * response interceptor, including the { status: "ok", result } unwrap.
 * Throws on an x-enc version this build doesn't know, so a cipher rotation
 * surfaces as a clear error instead of a silently-undecoded {e}.
 */
export function fastDecryptComixPayload(rawPath: string, payload: any, headers: Record<string, string> = {}): any {
    void rawPath;
    if (!(payload && typeof payload === "object" && typeof payload.e === "string")) return payload;
    const h = normalizeHeaders(headers);
    if (h["x-enc"] && h["x-enc"] !== X_ENC) {
        throw new Error("Comix x-enc " + h["x-enc"] + " is not supported (expected " + X_ENC + ") - the response cipher rotated; rerun the crypto pipeline");
    }

    const key = KEY ?? (KEY = b64Decode(KEY_B64));
    const ct = b64Decode(payload.e);
    const n = key.length;
    let k = ct.length >= 2 ? (((ct[0]! << 8) | ct[1]!) % n) : 0;
    const pt: number[] = new Array(Math.max(0, ct.length - 2));
    for (let i = 0; i < pt.length; i++) {
        pt[i] = ct[i + 2]! ^ key[k]!;
        if (++k === n) k = 0;
    }

    const parsed = JSON.parse(utf8Decode(pt));
    return parsed && typeof parsed === "object" && parsed.status === "ok" && "result" in parsed ? parsed.result : parsed;
}
