/* Generated by experiment/crypto-pipeline/generate.mjs. DO NOT EDIT BY HAND.
 * Bundle ID: e1619d65cd30
 * Algorithm: sbox-cbc (request signer), 3 rounds.
 * Round: out[i] = sbox[in[i] ^ out[i-1] ^ key[i % key.length]]   (out[-1] = iv)
 * Applied for stages N..1 (reverse of decrypt). Verified against the live token.
 */

const B64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

function b64Decode(s: string): number[] {
    const lookup: number[] = new Array(128).fill(-1);
    for (let i = 0; i < 64; i++) lookup[B64_CHARS.charCodeAt(i)] = i;
    const normalized = s.replace(/-/g, "+").replace(/_/g, "/");
    const out: number[] = [];
    let buf = 0, bits = 0;
    for (let i = 0; i < normalized.length; i++) {
        const c = normalized.charCodeAt(i);
        if (c === 61) break; // '='
        const v = lookup[c] ?? -1;
        if (v < 0) continue;
        buf = (buf << 6) | v;
        bits += 6;
        if (bits >= 8) { bits -= 8; out.push((buf >> bits) & 0xff); }
    }
    return out;
}

// Inverse-permutation cache, keyed by the stage's forward S-box base64.
const INV_CACHE: Record<string, number[]> = {};
function inverseSbox(tableB64: string): number[] {
    const cached = INV_CACHE[tableB64];
    if (cached) return cached;
    const table = b64Decode(tableB64);
    const inv: number[] = new Array(256).fill(0);
    for (let i = 0; i < 256; i++) inv[table[i]!] = i;
    INV_CACHE[tableB64] = inv;
    return inv;
}
const KEY_CACHE: Record<string, number[]> = {};
function keyBytes(keyB64: string): number[] {
    const cached = KEY_CACHE[keyB64];
    if (cached) return cached;
    const k = b64Decode(keyB64);
    KEY_CACHE[keyB64] = k;
    return k;
}

const SIGN_STAGES: { sboxB64: string; keyB64: string; iv: number }[] = [
    {
        "sboxB64": "ptLjLUx2s8gj2zX6EQfcSD3eAZMLwnGN+3KfPoYdZd93P9aSIonXWwAhOKxpFOcq77zhRid9vh57ltSkpXDGbY5Ph/N4/jcDCqLR7JpAFjTqshBaxF1564L8oBqBqiS0uAnLSymcPPTtV2qwzZSjkMq/zhhcOhxv4mfkvQ5/2adkJrZ8G5lzqSDDR5d19djp/9NDLg/xRNUCX2ChbFV+0FJoLGFeNqgxmxXouoOxxZW1rpgz2gw7WR/uyRKAryvyuzINa/gGY4WLwHpRBflBZq2r/VMTjCgwTVblOcxCz/BiGQRJ94oI4Pa5RRd0hI9YwS/mSp5QiCXdkZ23VMdObg==",
        "keyB64": "Q2LYjoyQGS35dmFB+qG6rpSsb7yImmHI471z",
        "iv": 195
    },
    {
        "sboxB64": "B9Z7BhJiMvetrsFIWelxVylPOfjhWvvLlyrfLn1wefmfK+/6nPQb0HQD4hrXAOAIb5ql/EeU2BP/0WBTO4A3lQsOQHZFHlyYgVWZ7I4gKIhRCmxrJhdKMQQ6GMS1tHOjcoK+YbqHst7cam4lLMheu+23p2MUNZKGqtKP8miRS9XmVqwPls1mz0bdk0wttiMNjX+ioCGeirx6QhE/Z064Np2Jyus4WxUv6sV4HDDo4ySwwxCk7jND8aGp1Mzkg4y55wxkfDzHi6hp9jRShBmFTdu9Sf6zkP2/VKYJmx8CHdrA5ckB8F91Fj4iztOrUPV3r0HCxrFtfgVYJ11l2T1E8w==",
        "keyB64": "qzqvvUW18oKCdY2vHbYnYe5fzQ==",
        "iv": 77
    },
    {
        "sboxB64": "xkjkuW7/2qxtPcSyMHYF77EizElx/mM4TjFsuhXo26eQDQB9Nfv1NirrKGF8ziDzaRkfVYottsmo/F07WVxyQd8+mkKlWLiYe/pTFwf2Ub4KRNimEgn9EEbXXyWJOsgmL64T7r+iZHpLKYufVyRqjVrQhOfAHuqRefFDvPeDR17NlBGzm/kMhj9zlsv4b6QOaDOTlbCvJzTHveAEiPAsw1Ce7a2XOZLsBg+FZt4h0p0duzdMgU3mSrdgcFLKHI7iATJUz6qHnLTTwqAjKxqZ1mdFqeWrgALddHdWPOPyFnX0f6GjT7VlQGJr1HjVGIzRj+l+3IIIxRThC9kuwQNbGw==",
        "keyB64": "Qafs81vMm8Pq2qA4RJq5Cw==",
        "iv": 107
    }
];

function signRound(data: number[], sboxB64: string, keyB64: string, iv: number): number[] {
    const table = b64Decode(sboxB64);
    const key = keyBytes(keyB64);
    const out: number[] = new Array(data.length);
    let prev = iv & 0xff;
    for (let i = 0; i < data.length; i++) {
        const idx = ((data[i]! & 0xff) ^ prev ^ key[i % key.length]!) & 0xff;
        const next = table[idx]! & 0xff;
        out[i] = next;
        prev = next;
    }
    return out;
}

function b64UrlEncode(bytes: number[]): string {
    let out = "", i = 0;
    for (; i + 2 < bytes.length; i += 3) {
        const n = (bytes[i]! << 16) | (bytes[i + 1]! << 8) | bytes[i + 2]!;
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]! + B64_CHARS[(n >> 6) & 63]! + B64_CHARS[n & 63]!;
    }
    if (i + 1 === bytes.length) {
        const n = bytes[i]! << 16;
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]!;
    } else if (i + 2 === bytes.length) {
        const n = (bytes[i]! << 16) | (bytes[i + 1]! << 8);
        out += B64_CHARS[(n >> 18) & 63]! + B64_CHARS[(n >> 12) & 63]! + B64_CHARS[(n >> 6) & 63]!;
    }
    return out.replace(/\+/g, "-").replace(/\//g, "_");
}

function normalizeSignPath(rawPath: string): string {
    return rawPath
        .replace(/^https?:\/\/[^/]+/, "")
        .replace(/^\/api\/v1/, "")
        .split("?")[0]!;
}

function bytesFromString(s: string): number[] {
    const out: number[] = new Array(s.length);
    for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i) & 0xff;
    return out;
}

/** Produce the comix.to `_` signing token for an API path. */
export function fastGenerateHash(rawPath: string): string {
    const path = normalizeSignPath(rawPath);
    let data = bytesFromString(path);
    for (let r = SIGN_STAGES.length - 1; r >= 0; r--) {
        const s = SIGN_STAGES[r]!;
        data = signRound(data, s.sboxB64, s.keyB64, s.iv);
    }
    return b64UrlEncode(data);
}
