// Comix.to image-tile descrambler.
//
// Two CDN path variants (both on *.wowpicN.store):
//   /si/<token>/<page>.webp  — clean image, no scramble headers.
//   /sii/<token>/<page>.webp — scrambled image, carries scramble headers.
//
// The interceptor regex must match BOTH (/sii?/). A shuffled /sii/ response
// carries:
//
//   X-Scramble-Seed:  <uint32, decimal>   e.g. "3121655837"
//   X-Scramble-Grid:  <cols>x<rows>       e.g. "5x5"
//
// The shuffle is row-major over a `cols * rows` tile grid, generated by a
// Fisher-Yates backward pass seeded with a Numerical Recipes "ranqd1" LCG:
//
//   state_{n+1} = (state_n * 1664525 + 1013904223) mod 2^32
//   for i from N-1 down to 1:
//     state = step(state)
//     j = state mod (i + 1)
//     swap arr[i], arr[j]
//
// `arr` starts as [0..N-1] and ends as the forward scramble permutation P,
// where scrambled_tile[i] = clean_tile[P[i]]. To descramble, walk scrambled
// tile by tile and place scrambled[i] at clean position P[i] — i.e. read
// `inverse(P)` indexed by clean position.
//
// Verified byte-exact against 15 saved pages from chapter 9908208.

export interface ScrambleParams {
  seed: number;
  cols: number;
  rows: number;
}

// Forward scramble permutation: scrambled[i] = clean[P[i]].
export function computeScramblePerm(seed: number, tileCount: number): number[] {
  let state = seed >>> 0;
  const arr = new Array<number>(tileCount);
  for (let i = 0; i < tileCount; i++) arr[i] = i;
  for (let i = tileCount - 1; i > 0; i--) {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    const j = state % (i + 1);
    const tmp = arr[i]!;
    arr[i] = arr[j]!;
    arr[j] = tmp;
  }
  return arr;
}

// For each clean tile position, the scrambled tile to copy from:
// clean[i] = scrambled[descrambleLookup[i]].
export function computeDescrambleLookup(seed: number, tileCount: number): number[] {
  const P = computeScramblePerm(seed, tileCount);
  const inv = new Array<number>(tileCount);
  for (let i = 0; i < tileCount; i++) inv[P[i]!] = i;
  return inv;
}

// Parse "5x5" -> { cols: 5, rows: 5 }. Returns null if malformed.
export function parseScrambleGrid(grid: string): { cols: number; rows: number } | null {
  const m = /^\s*(\d+)\s*x\s*(\d+)\s*$/i.exec(grid);
  if (!m) return null;
  const cols = parseInt(m[1]!, 10);
  const rows = parseInt(m[2]!, 10);
  if (!Number.isFinite(cols) || !Number.isFinite(rows) || cols <= 0 || rows <= 0) return null;
  return { cols, rows };
}

// Pull scramble params from a response's headers. Case-insensitive.
// Returns null when the headers are absent or malformed — the image is
// then either unscrambled or unparseable and should be passed through.
export function readScrambleHeaders(
  headers: Record<string, string | undefined> | undefined,
): ScrambleParams | null {
  if (!headers) return null;
  let seedStr: string | undefined;
  let gridStr: string | undefined;
  for (const key of Object.keys(headers)) {
    const v = headers[key];
    if (typeof v !== "string") continue;
    const lk = key.toLowerCase();
    if (lk === "x-scramble-seed") seedStr = v;
    else if (lk === "x-scramble-grid") gridStr = v;
  }
  if (!seedStr || !gridStr) return null;
  const seed = parseInt(seedStr, 10);
  if (!Number.isFinite(seed) || seed < 0) return null;
  const grid = parseScrambleGrid(gridStr);
  if (!grid) return null;
  return { seed, cols: grid.cols, rows: grid.rows };
}
