/* Generated by experiment/BuildComixFastDecrypt.ts.
 * Bundle ID: 5aeea05f1a81
 * Algorithm: sbox-cbc-inverse
 * Pipeline order: sbox-cbc-inverse
 * This is the de-VM'd Comix response decrypt pipeline.
 */

const B64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const SBOX_INVERSE_STAGES = [
    {
        "tableB64": "Cd5hNQ9D7kk7nV28BHBtDgsihk4SwOjgqf3NJHl/rfmv3x9EFdoqcXTWWTR2sqz47f/hQjompqDs/Jw/VCiigydpAkix2EBMj2XC9ef2jaHMWL9cYDE9Ixu6GL541+lfjO9qq7v3FrRSA5KR/g30Zi5jEbV+ByxBbPIM+n0r27aaxIgUiwow0qW3h4CQHVEQxdPVweWFb+JNT4lynxejSjfjAbgI5gWza3P7SyAzyZglAJ5olVN81FpVypbwgXVnp0UpYuQ58VdWMoq5sF6ZOG4ePssG0arqrnp3yC3HRoJH81CbIRzO3ZOOvdk8z3vQE5SEw6QZ3Fvrly+oGjZkxg==",
        "keyB64": "ISTlGCRAVsibq25re09OwSeJig==",
        "iv": 142
    },
    {
        "tableB64": "JsG5oul0GpwSZLiHpv5ucFlX3ve9MJo6JcVNQaHH9uNbnhG1G/UcBikWF4GJWM2/eakOPWdsglEiMcQYCrvOP9nmM1SXHUgtYxT/OWbhyisFR9wkCUMgeBUfvNJzDP2okXatQJP7hErsKmpLep8E5cLajAgsAn7Qqic0iI0eX6uuE1X5XAE2Ay4ATuTD6utlXkVE1pTvT0ywy8BSU2ANjttrd6A7zJXf0YDYEKO38ziFUO5xYfGxhijy5wsPRkm617T66K/VnVYH9OCkf7Yh/FqK06fPdSN7j/g31BmZkpDibULIMr6ylvCbpX1oPpjdbzyLNcZirHKDXS/J7bNpfA==",
        "keyB64": "JOnpDPMZJjt/V1Lcy/aJz4dj+2bO5ODBOqR8VQ==",
        "iv": 111
    },
    {
        "tableB64": "TBqH6PGKZpVJtSPsw7dIF7yqx2k5VwgNRDeaEO9zhsH5d0ElVbBTP0b8kd+I0hJRrOoqLWqoTaJyMjv30YIpv9PpS3SFfUr1Yu6Orv7AKC6Na8n71P2kyIP0pZMx8Pi4wgcdnr0nUqcOtjwkek9A+sajs+F1n0Xl1h6LDFBWfF/teJIbzdUwqyCJmGE180Mr3a3kurSM2jTyWxHMyrJd45aboBwYr2j2sbkVC05vQjiQec7nVAJ7FgoABCxe18/L4H5lRyF/PlovWKZj3P86BWTmIgnrPZTEndnQhHBxXBMBZw+722zYoeK+M8WAgamZFJwGdiY2YG2P3gNuWZcfGQ==",
        "keyB64": "rHDaYeCnpP0WKdrXiVhVCyLlx9Uq+FQMtic=",
        "iv": 145
    }
];
let SBOX_INVERSE_RUNTIME: { table: number[]; inverseTable: number[]; key: number[]; iv: number }[] | null = null;

function b64Decode(s: string): number[] {
    const lookup: number[] = new Array(128).fill(-1);
    for (let i = 0; i < 64; i++) lookup[B64_CHARS.charCodeAt(i)] = i;
    const normalized = s.replace(/-/g, "+").replace(/_/g, "/");
    const out: number[] = [];
    let buf = 0, bits = 0;
    for (let i = 0; i < normalized.length; i++) {
        const c = normalized.charCodeAt(i);
        if (c === 61) break;
        const v = lookup[c] ?? -1;
        if (v < 0) continue;
        buf = (buf << 6) | v;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out.push((buf >> bits) & 0xff);
        }
    }
    return out;
}

function bytesToBinaryString(bytes: number[]): string {
    let out = "";
    for (let i = 0; i < bytes.length; i += 8192) {
        out += String.fromCharCode(...bytes.slice(i, i + 8192));
    }
    return out;
}

function getSboxInverseRuntime() {
    if (SBOX_INVERSE_RUNTIME === null) {
        SBOX_INVERSE_RUNTIME = SBOX_INVERSE_STAGES.map(stage => {
            const table = b64Decode(stage.tableB64);
            const inverseTable: number[] = new Array(256).fill(0);
            for (let i = 0; i < 256; i++) inverseTable[table[i]!] = i;
            return { table, inverseTable, key: b64Decode(stage.keyB64), iv: stage.iv };
        });
    }
    return SBOX_INVERSE_RUNTIME;
}

function applySboxCbcInverseStage(data: number[], stage: { inverseTable: number[]; key: number[]; iv: number }): number[] {
    const out: number[] = new Array(data.length);
    let prev = stage.iv & 0xff;
    for (let i = 0; i < data.length; i++) {
        const cipherByte = data[i]! & 0xff;
        const idx = stage.inverseTable[cipherByte]! & 0xff;
        out[i] = (idx ^ stage.key[i % stage.key.length]! ^ prev) & 0xff;
        prev = cipherByte;
    }
    return out;
}

function normalizeHeaders(headers: Record<string, string>): Record<string, string> {
    const out: Record<string, string> = {};
    for (const key of Object.keys(headers ?? {})) out[key.toLowerCase()] = String(headers[key]);
    return out;
}

export function fastDecryptComixPayload(rawPath: string, payload: any, headers: Record<string, string> = {}): any {
    void rawPath;
    if (!(payload && typeof payload === "object" && "e" in payload)) return payload;
    const normalizedHeaders = normalizeHeaders(headers);
    if (normalizedHeaders["x-enc"] && normalizedHeaders["x-enc"] !== "1") return payload;

    let data = b64Decode(String(payload.e ?? ""));
    const stages = getSboxInverseRuntime();
    for (const stage of stages) data = applySboxCbcInverseStage(data, stage);

    const parsed = JSON.parse(decodeURIComponent(bytesToBinaryString(data)));
    return parsed && typeof parsed === "object" && parsed.status === "ok" ? parsed.result : parsed;
}
